/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pacientessoykpaz.frontend.controlCuotas;

import com.pacientessoykpaz.backend.controldata.ControlDatos;
import com.pacientessoykpaz.backend.entidad.Cuota;
import com.pacientessoykpaz.frontend.WindowSoyKpaz;
import com.pacientessoykpaz.util.ManejoRutas;
import com.pacientessoykpaz.util.Utiles;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Luis
 */
public class EditCuotaWindow extends javax.swing.JFrame {

    private ButtonGroup group;
    private ControlDatos controlDatos;
    private ManejoRutas rutas;
    private String path;
    private Cuota cuota;
    private CuotasWindow cuotasWindow;

    /**
     * Creates new form EditCuotaWindow
     *
     * @param controlDatos
     * @param cuota
     * @param cuotasWindow
     */
    public EditCuotaWindow(ControlDatos controlDatos, Cuota cuota, CuotasWindow cuotasWindow) {
        initComponents();
        setLocationRelativeTo(null);
        this.controlDatos = controlDatos;
        this.rutas = new ManejoRutas();

        this.path = "";
        this.cuotasWindow = cuotasWindow;
        this.cuota = cuota;

        this.group = new ButtonGroup();
        this.group.add(radioBoleta);
        this.group.add(radioEfectivo);

        radioEfectivo.setSelected(true);
        //establecer el icon de la app cuando se está usando
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/ong.png")));
        try {
            //para que se parezca al tema de sistema operativo
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(WindowSoyKpaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(WindowSoyKpaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        radioEfectivo = new javax.swing.JRadioButton();
        radioBoleta = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtFile = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new rojeru_san.RSButton();
        btnCancel = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PAGO DE CUOTA MENSUAL"));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        radioEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioEfectivo.setText("Efectivo");
        jPanel2.add(radioEfectivo);

        radioBoleta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioBoleta.setText("Boleta");
        jPanel2.add(radioBoleta);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Seleccionar archivo");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);
        jPanel2.add(txtFile);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSave.setText("Guardar cambios");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave);

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCancel.setText("Cancelar X");
        btnCancel.setColorHover(new java.awt.Color(255, 102, 102));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        path = rutas.pathChoserOpen(null);
        if (!path.equals("")) {
            File file = new File(path);
            txtFile.setText(file.getName());
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if (radioBoleta.isSelected()) {
            cuota.setTipoPago(Utiles.BOLETA);
        } else if (radioEfectivo.isSelected()) {
            cuota.setTipoPago(Utiles.EFECTIVO);
        }
        cuota.setEstado(Utiles.CUOTA_CANCELADA);
        int opcion = (int) JOptionPane.showInternalConfirmDialog(
                null,
                "¿Desea guardar los cambios?",
                "GUARDAR CAMBIOS",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE);
        if (opcion == 0) {

            if (!path.equals("")) {
                try {
                    File file = new File(path);
                    InputStream in = new FileInputStream(file);
                    String tipo = file.getName().substring(file.getName().lastIndexOf(".") + 1);
                    byte[] arrayBytes = in.readAllBytes();
                    cuota.setFileBytes(arrayBytes);
                    cuota.setTipoArchivo(tipo);

                    if (controlDatos.getCuotaDB().update(cuota)) {
                        controlDatos.mensajeOk();
                    } else {
                        controlDatos.mensajeNoOk();
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(EditCuotaWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(EditCuotaWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                int opcion2 = (int) JOptionPane.showInternalConfirmDialog(
                        null,
                        "¿Desea guardar los cambios SIN HABER SELECCIONADO UNA BOLETA DE PAGO O RECIBO?",
                        "NO SE HA SELECCIONADO ALGÚN ARCHIVO",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
                if (opcion2 == 0) {
                    if (controlDatos.getCuotaDB().updateWhitoutFile(cuota)) {
                    } else {
                        controlDatos.mensajeNoOk();
                    }
                }
            }
        }
        this.cuotasWindow.setListcuotas(controlDatos.getCuotaDB().getList(Utiles.CUOTA_CANCELADA));
        this.cuotasWindow.llenarTablaCuotas(this.cuotasWindow.getListcuotas());

    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.setVisible(false);
        this.cuotasWindow.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.cuotasWindow.setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnCancel;
    private rojeru_san.RSButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton radioBoleta;
    private javax.swing.JRadioButton radioEfectivo;
    private javax.swing.JTextField txtFile;
    // End of variables declaration//GEN-END:variables
}
