/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pacientessoykpaz.frontend;

import com.pacientessoykpaz.backend.controldata.ControlDatos;
import com.pacientessoykpaz.backend.entidad.Condicion;
import com.pacientessoykpaz.backend.entidad.CondicionPaciente;
import com.pacientessoykpaz.backend.entidad.Encargado;
import com.pacientessoykpaz.backend.entidad.Paciente;
import com.pacientessoykpaz.backend.entidad.PacienteInfo;
import com.pacientessoykpaz.backend.entidad.Terapista;
import com.pacientessoykpaz.util.Utiles;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class WindowSoyKpaz extends javax.swing.JFrame {

    private Utiles utiles;
    private ControlDatos controlDatos;
    private Encargado encargadoAuxi;
    private ButtonGroup group1;
    private ButtonGroup group2;
    private List<PacienteInfo> listPacientes;
    private DefaultTableModel dfModel;

    /**
     * Creates new form WindowSoyKpaz
     */
    public WindowSoyKpaz() {
        initComponents();

        this.dfModel = new DefaultTableModel();

        establecerFocus();
        setLocationRelativeTo(null);

        this.utiles = new Utiles();
        this.controlDatos = new ControlDatos();

        group1 = new ButtonGroup();
        group1.add(radio100);
        group1.add(radio50);
        group1.add(radioNoBecado);

        group2 = new ButtonGroup();
        group2.add(radioIngresos1);
        group2.add(radioIngresos2);
        group2.add(radioIngresos3);

        this.listPacientes = new ArrayList<>();
        this.listPacientes = this.controlDatos.getPacienteInfoDB().getPacientes();
        /**
         * Establecer iconos
         */
        utiles.ponerIconoLabel(label1, "/img/soykapaz.jpeg");

        llenarCondiciones(listCondiciones);
        llenarComboTerapista(comboTerapistas);
        /**
         * Llenar tablas
         */
        llenarTablaPacientes(this.listPacientes);
        llenarTablaTerapistas(this.controlDatos.getTerapistaDB().getTerapistas());
        //establecer el icon de la app cuando se está usando
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/ong.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        panelNuevoPaciente = new javax.swing.JPanel();
        labelNuevoPaciente = new javax.swing.JLabel();
        panelPacientes = new javax.swing.JPanel();
        labelPacientes = new javax.swing.JLabel();
        panelTerapistas = new javax.swing.JPanel();
        labelTerapistas = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCarne = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        radio100 = new javax.swing.JRadioButton();
        radio50 = new javax.swing.JRadioButton();
        radioNoBecado = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCondiciones = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        txtOtraCondición = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEnfermedad = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtDpiEncargado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNameEncargado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        radioIngresos1 = new javax.swing.JRadioButton();
        radioIngresos2 = new javax.swing.JRadioButton();
        radioIngresos3 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboTerapistas = new javax.swing.JComboBox<>();
        checkHabla = new javax.swing.JCheckBox();
        checkOcupacional = new javax.swing.JCheckBox();
        checkPsicologico = new javax.swing.JCheckBox();
        btnSaveData = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePacientes = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        labelVerInformación = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTerapistas = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtdpiTerapista = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNombreTerapista = new javax.swing.JTextField();
        btnSaveTerapista = new javax.swing.JButton();
        btnClearTerapista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoyKPazONG");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(277, 325));

        panelNuevoPaciente.setBackground(new java.awt.Color(51, 204, 0));
        panelNuevoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelNuevoPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelNuevoPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelNuevoPacienteMouseExited(evt);
            }
        });

        labelNuevoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        labelNuevoPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNuevoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNuevoPaciente.setText("Nuevo paciente");
        labelNuevoPaciente.setToolTipText("");
        labelNuevoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNuevoPacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelNuevoPacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelNuevoPacienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelNuevoPacienteLayout = new javax.swing.GroupLayout(panelNuevoPaciente);
        panelNuevoPaciente.setLayout(panelNuevoPacienteLayout);
        panelNuevoPacienteLayout.setHorizontalGroup(
            panelNuevoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNuevoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelNuevoPacienteLayout.setVerticalGroup(
            panelNuevoPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNuevoPacienteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelNuevoPaciente)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelPacientes.setBackground(new java.awt.Color(51, 204, 0));
        panelPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelPacientesMouseExited(evt);
            }
        });

        labelPacientes.setBackground(new java.awt.Color(255, 255, 255));
        labelPacientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPacientes.setText("Pacientes");
        labelPacientes.setToolTipText("");
        labelPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelPacientesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPacientesLayout = new javax.swing.GroupLayout(panelPacientes);
        panelPacientes.setLayout(panelPacientesLayout);
        panelPacientesLayout.setHorizontalGroup(
            panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPacientesLayout.setVerticalGroup(
            panelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacientesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelPacientes)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelTerapistas.setBackground(new java.awt.Color(51, 204, 0));
        panelTerapistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTerapistasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelTerapistasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelTerapistasMouseExited(evt);
            }
        });

        labelTerapistas.setBackground(new java.awt.Color(255, 255, 255));
        labelTerapistas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTerapistas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTerapistas.setText("Terapistas");
        labelTerapistas.setToolTipText("");
        labelTerapistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTerapistasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelTerapistasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelTerapistasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelTerapistasLayout = new javax.swing.GroupLayout(panelTerapistas);
        panelTerapistas.setLayout(panelTerapistasLayout);
        panelTerapistasLayout.setHorizontalGroup(
            panelTerapistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerapistasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTerapistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTerapistasLayout.setVerticalGroup(
            panelTerapistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTerapistasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelTerapistas)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNuevoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTerapistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNuevoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTerapistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setEnabled(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrar nuevo paciente");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos personales y tipo de programa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("* Carné:");

        jLabel6.setText("* Nombre:");

        jLabel7.setText("* Fecha de nacimiento:");

        jLabel8.setText("* Edad:");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        dateChooser.setDateFormatString("y-M-d");
        dateChooser.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                dateChooserComponentAdded(evt);
            }
        });
        dateChooser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                dateChooserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        dateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateChooserMouseClicked(evt);
            }
        });
        dateChooser.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dateChooserInputMethodTextChanged(evt);
            }
        });

        jLabel15.setText("Tipo de programa:");

        radio100.setText("100 % becado");
        radio100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio100ActionPerformed(evt);
            }
        });

        radio50.setText("50 % becado");
        radio50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio50ActionPerformed(evt);
            }
        });

        radioNoBecado.setText("No becado");
        radioNoBecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNoBecadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addComponent(txtCarne))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAge)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(radio100)
                        .addGap(18, 18, 18)
                        .addComponent(radio50, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioNoBecado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radio50)
                        .addComponent(radioNoBecado))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(radio100)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Condición y alguna enfermedad crónica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel2.setText("* Condición:");

        listCondiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listCondicionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listCondiciones);

        jLabel12.setText("Otra (especifíque):");

        jLabel16.setText("Enfermedad crónica:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtOtraCondición, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(txtEnfermedad))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtOtraCondición, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del encargado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtDpiEncargado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDpiEncargadoKeyTyped(evt);
            }
        });

        jLabel4.setText("* DPI:");

        jLabel9.setText("* Nombre:");

        txtNameEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameEncargadoActionPerformed(evt);
            }
        });

        jLabel10.setText("* Dirección:");

        jLabel11.setText("* Teléfono:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jLabel14.setText("Condición socio-económica:");

        radioIngresos1.setText("Ingresos inferiores a Q 1,000");
        radioIngresos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIngresos1ActionPerformed(evt);
            }
        });

        radioIngresos2.setText("Ingresos superiores a Q 1,000");

        radioIngresos3.setText("No tiene ingresos fijos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(radioIngresos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioIngresos2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNameEncargado))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDpiEncargado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radioIngresos3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefono))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDpiEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNameEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(radioIngresos1))
                    .addComponent(radioIngresos3)
                    .addComponent(radioIngresos2))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Terapista y tipo de terapia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel5.setText("Terapista:");

        jLabel13.setText("Terapia a recibir:");

        checkHabla.setText("Habla");
        checkHabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHablaActionPerformed(evt);
            }
        });

        checkOcupacional.setText("Ocupacional");

        checkPsicologico.setText("Psicológico");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboTerapistas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkHabla)
                .addGap(18, 18, 18)
                .addComponent(checkOcupacional)
                .addGap(25, 25, 25)
                .addComponent(checkPsicologico))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(checkHabla)
                        .addComponent(checkOcupacional)
                        .addComponent(checkPsicologico))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(comboTerapistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnSaveData.setBackground(new java.awt.Color(0, 204, 51));
        btnSaveData.setText("Guardar cambios");
        btnSaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDataActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 255, 0));
        btnClear.setText("Limpiar campos");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSaveData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnSaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel6);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carné", "Nombre", "Fecha de nacimiento", "Tipo de grograma", "Terapista", "Terapia", "Encargado", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePacientes.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tablePacientes);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        labelVerInformación.setText("Ver información");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelVerInformación, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelVerInformación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel8);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        tableTerapistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DPI", "TERAPISTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTerapistas.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tableTerapistas);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar nuevo terapista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel17.setText("DPI:");

        txtdpiTerapista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdpiTerapistaKeyTyped(evt);
            }
        });

        jLabel18.setText("Nombre:");

        btnSaveTerapista.setBackground(new java.awt.Color(51, 204, 0));
        btnSaveTerapista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSaveTerapista.setText("Guardar datos");
        btnSaveTerapista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTerapistaActionPerformed(evt);
            }
        });

        btnClearTerapista.setBackground(new java.awt.Color(255, 255, 102));
        btnClearTerapista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClearTerapista.setText("Limpiar campos");
        btnClearTerapista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTerapistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveTerapista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtdpiTerapista))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreTerapista, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                    .addComponent(btnClearTerapista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtdpiTerapista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtNombreTerapista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveTerapista)
                .addGap(18, 18, 18)
                .addComponent(btnClearTerapista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab3", jPanel14);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelNuevoPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNuevoPacienteMouseEntered
        // TODO add your handling code here:
        panelNuevoPaciente.setBackground(new Color(85, 255, 51));
    }//GEN-LAST:event_panelNuevoPacienteMouseEntered

    private void labelNuevoPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoPacienteMouseExited
        // TODO add your handling code here:
        panelNuevoPaciente.setBackground(new Color(51, 204, 0));
    }//GEN-LAST:event_labelNuevoPacienteMouseExited

    private void panelNuevoPacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNuevoPacienteMouseExited
        // TODO add your handling code here:
        panelNuevoPaciente.setBackground(new Color(51, 204, 0));
    }//GEN-LAST:event_panelNuevoPacienteMouseExited

    private void labelNuevoPacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoPacienteMouseEntered
        // TODO add your handling code here:
        panelNuevoPaciente.setBackground(new Color(85, 255, 51));
    }//GEN-LAST:event_labelNuevoPacienteMouseEntered

    private void labelPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPacientesMouseEntered
        // TODO add your handling code here:
        panelPacientes.setBackground(new Color(85, 255, 51));
    }//GEN-LAST:event_labelPacientesMouseEntered

    private void labelPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPacientesMouseExited
        // TODO add your handling code here:
        panelPacientes.setBackground(new Color(51, 204, 0));
    }//GEN-LAST:event_labelPacientesMouseExited

    private void panelPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPacientesMouseEntered
        // TODO add your handling code here:
        panelPacientes.setBackground(new Color(85, 255, 51));
    }//GEN-LAST:event_panelPacientesMouseEntered

    private void panelPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPacientesMouseExited
        // TODO add your handling code here:
        panelPacientes.setBackground(new Color(51, 204, 0));
    }//GEN-LAST:event_panelPacientesMouseExited

    private void labelTerapistasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTerapistasMouseEntered
        // TODO add your handling code here:
        panelTerapistas.setBackground(new Color(85, 255, 51));
    }//GEN-LAST:event_labelTerapistasMouseEntered

    private void labelTerapistasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTerapistasMouseExited
        // TODO add your handling code here:
        panelTerapistas.setBackground(new Color(51, 204, 0));
    }//GEN-LAST:event_labelTerapistasMouseExited

    private void panelTerapistasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTerapistasMouseEntered
        // TODO add your handling code here:
        panelTerapistas.setBackground(new Color(85, 255, 51));
    }//GEN-LAST:event_panelTerapistasMouseEntered

    private void panelTerapistasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTerapistasMouseExited
        // TODO add your handling code here:
        panelTerapistas.setBackground(new Color(51, 204, 0));
    }//GEN-LAST:event_panelTerapistasMouseExited

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtNameEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameEncargadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameEncargadoActionPerformed

    private void listCondicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listCondicionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listCondicionesMouseClicked

    private void radio100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio100ActionPerformed

    private void radio50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio50ActionPerformed

    private void radioNoBecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNoBecadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNoBecadoActionPerformed

    private void btnSaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDataActionPerformed
        // TODO add your handling code here:
        JTextField auxi = (JTextField) dateChooser.getDateEditor().getUiComponent();
        JRadioButton auxiBtn = new JRadioButton();
        JRadioButton auxiBtn2 = new JRadioButton();
        boolean seleccionado = false;
        boolean ingresoSeleecionado = false;
        if (group1.isSelected(radio100.getModel())) {
            auxiBtn = radio100;
            seleccionado = true;
        } else if (group1.isSelected(radio50.getModel())) {
            auxiBtn = radio50;
            seleccionado = true;
        } else if (group1.isSelected(radioNoBecado.getModel())) {
            auxiBtn = radioNoBecado;
            seleccionado = true;
        }
        if (group2.isSelected(radioIngresos1.getModel())) {
            ingresoSeleecionado = true;
            auxiBtn2 = radioIngresos1;
        } else if (group2.isSelected(radioIngresos2.getModel())) {
            ingresoSeleecionado = true;
            auxiBtn2 = radioIngresos2;
        } else if (group2.isSelected(radioIngresos3.getModel())) {
            ingresoSeleecionado = true;
            auxiBtn2 = radioIngresos3;
        }
        //verificamos si se ha seleccionado 
        if (seleccionado && ingresoSeleecionado) {
            //agreamos al paciente
            String[] datosTerapista = comboTerapistas.getSelectedItem().toString().split(",");
            String dpiterapista = datosTerapista[0];
            System.out.println("dpi terapista " + dpiterapista);
            String terapia = " ";
            if (checkHabla.isSelected()) {
                terapia += checkHabla.getText();
                terapia += " ";
            }
            if (checkOcupacional.isSelected()) {
                terapia += checkOcupacional.getText();
                terapia += " ";
            }
            if (checkPsicologico.isSelected()) {
                terapia += checkPsicologico.getText();
                terapia += " ";
            }
            //verficamos si el encargado ya existe para no repetir datos
            if (encargadoAuxi == null) {
                //agregamos al encargado 
                controlDatos.getEncargadoDB().insert(
                        Encargado.builder().
                                dpi(txtDpiEncargado.getText()).
                                nombre(txtNameEncargado.getText()).
                                telefono(txtTelefono.getText()).
                                direccion(txtDireccion.getText()).
                                condicionEconomica(auxiBtn2.getText()).
                                rutaDocumento("").build());
            } else {
                controlDatos.getEncargadoDB().insert(
                        Encargado.builder().
                                dpi(txtDpiEncargado.getText()).
                                nombre(txtNameEncargado.getText()).
                                telefono(txtTelefono.getText()).
                                direccion(txtDireccion.getText()).
                                condicionEconomica(auxiBtn2.getText()).
                                rutaDocumento("").build());
            }
            //agregamos al paciente
            Paciente nuevoPaciente = Paciente.builder().
                    carne(txtCarne.getText()).
                    nombre(txtName.getText()).
                    edad(Integer.parseInt(txtAge.getText())).
                    fechaNacimiento(auxi.getText()).
                    tipoPrograma(auxiBtn.getText()).
                    dpiTerapista(dpiterapista).
                    terapia(terapia).
                    dpiEncargado(txtDpiEncargado.getText()).
                    enfermedadCronica(txtEnfermedad.getText()).
                    build();
            System.out.println(nuevoPaciente.toString());
            if (controlDatos.getPacienteDB().insert(
                    nuevoPaciente)) {

                //agregamos su condicion-física
                if (!txtOtraCondición.getText().isBlank()) {
                    //creamos la nueva en la base de datos
                    controlDatos.getCondicionDB().insert(Condicion.builder().nombre(txtOtraCondición.getText()).build());
                    //agreamos al paciente el nuevo y el resto
                    controlDatos.getCondicionPacienteDB().insert(
                            CondicionPaciente.builder().
                                    nombreCondicion(txtOtraCondición.getText()).
                                    carnePaciente(txtCarne.getText()).
                                    build());
                    agregarOtrasCondiciones();
                } else {
                    agregarOtrasCondiciones();
                }
                JOptionPane.showMessageDialog(null,
                        "Se guardó correctamente los datos.",
                        "DATOS GUARDADOS.", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null,
                        "No pudimos guardar los datos, consulte con el programador.",
                        "ERROR AL GUARDAR DATOS",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar el tipo de programa o el rango de ingresos del encargado",
                    "SELECCIONAR PROGRAMA",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnSaveDataActionPerformed

    private void dateChooserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_dateChooserAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_dateChooserAncestorAdded

    private void dateChooserComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_dateChooserComponentAdded

    }//GEN-LAST:event_dateChooserComponentAdded

    private void dateChooserInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dateChooserInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_dateChooserInputMethodTextChanged

    private void dateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateChooserMouseClicked
        // TODO add your handling code here:
        JTextField auxi = (JTextField) dateChooser.getDateEditor().getUiComponent();
        System.out.println(auxi.getText());
    }//GEN-LAST:event_dateChooserMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtCarne.setText("");
        txtAge.setText("");
        txtDireccion.setText("");
        txtDpiEncargado.setText("");
        txtEnfermedad.setText("");
        txtName.setText("");
        txtNameEncargado.setText("");
        txtOtraCondición.setText("");
        txtTelefono.setText("");
        this.encargadoAuxi = null;
    }//GEN-LAST:event_btnClearActionPerformed

    private void checkHablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkHablaActionPerformed

    private void txtDpiEncargadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDpiEncargadoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDpiEncargadoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void radioIngresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIngresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioIngresos1ActionPerformed

    private void panelNuevoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNuevoPacienteMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_panelNuevoPacienteMouseClicked

    private void labelNuevoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoPacienteMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_labelNuevoPacienteMouseClicked

    private void panelPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPacientesMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        llenarTablaPacientes(listPacientes);
    }//GEN-LAST:event_panelPacientesMouseClicked

    private void labelPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPacientesMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        llenarTablaPacientes(listPacientes);
    }//GEN-LAST:event_labelPacientesMouseClicked

    private void txtdpiTerapistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdpiTerapistaKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdpiTerapistaKeyTyped

    private void btnClearTerapistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTerapistaActionPerformed
        // TODO add your handling code here:
        txtNombreTerapista.setText("");
        txtdpiTerapista.setText("");
    }//GEN-LAST:event_btnClearTerapistaActionPerformed

    private void btnSaveTerapistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTerapistaActionPerformed
        // TODO add your handling code here:
        Terapista t = Terapista.builder().nombre(txtNombreTerapista.getText()).dpi(txtdpiTerapista.getText()).build();
        if (controlDatos.getTerapistaDB().insert(t)) {
            JOptionPane.showMessageDialog(null,
                    "Se guardó correctamente los datos.",
                    "DATOS GUARDADOS.", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "No pudimos guardar correctamente los datos.",
                    "DATOS NO GUARDADOS.", JOptionPane.INFORMATION_MESSAGE);
        }
        llenarTablaTerapistas(controlDatos.getTerapistaDB().getTerapistas());
    }//GEN-LAST:event_btnSaveTerapistaActionPerformed

    private void labelTerapistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTerapistasMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_labelTerapistasMouseClicked

    private void panelTerapistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTerapistasMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_panelTerapistasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClearTerapista;
    private javax.swing.JButton btnSaveData;
    private javax.swing.JButton btnSaveTerapista;
    private javax.swing.JCheckBox checkHabla;
    private javax.swing.JCheckBox checkOcupacional;
    private javax.swing.JCheckBox checkPsicologico;
    private javax.swing.JComboBox<String> comboTerapistas;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel labelNuevoPaciente;
    private javax.swing.JLabel labelPacientes;
    private javax.swing.JLabel labelTerapistas;
    private javax.swing.JLabel labelVerInformación;
    private javax.swing.JList<String> listCondiciones;
    private javax.swing.JPanel panelNuevoPaciente;
    private javax.swing.JPanel panelPacientes;
    private javax.swing.JPanel panelTerapistas;
    private javax.swing.JRadioButton radio100;
    private javax.swing.JRadioButton radio50;
    private javax.swing.JRadioButton radioIngresos1;
    private javax.swing.JRadioButton radioIngresos2;
    private javax.swing.JRadioButton radioIngresos3;
    private javax.swing.JRadioButton radioNoBecado;
    private javax.swing.JTable tablePacientes;
    private javax.swing.JTable tableTerapistas;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCarne;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDpiEncargado;
    private javax.swing.JTextField txtEnfermedad;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameEncargado;
    private javax.swing.JTextField txtNombreTerapista;
    private javax.swing.JTextField txtOtraCondición;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtdpiTerapista;
    // End of variables declaration//GEN-END:variables

    private void establecerFocus() {
        JTextField auxiText = (JTextField) dateChooser.getDateEditor().getUiComponent();
        KeyListener focus;
        focus = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
                if (e.getKeyCode() == 10) {
                    if (e.getComponent().equals(txtCarne)) {
                        txtName.requestFocus();
                    } else if (e.getComponent().equals(txtName)) {
                        dateChooser.requestFocus();
                    } else if (e.getComponent().equals(dateChooser.getDateEditor().getUiComponent())) {
                        txtAge.setText(controlDatos.getFechaDB().getAñosTranscurridos(auxiText.getText()));
                        txtAge.requestFocus();
                    } else if (e.getComponent().equals(txtAge)) {
                        radio100.requestFocus();
                    } else if (e.getComponent().equals(txtDpiEncargado)) {
                        //en caso de que ya existe los datos del encargado
                        encargadoAuxi = controlDatos.getEncargadoDB().getEncargado(txtDpiEncargado.getText());
                        if (encargadoAuxi != null) {
                            txtNameEncargado.setText(encargadoAuxi.getNombre());
                            txtDireccion.setText(encargadoAuxi.getDireccion());
                            txtTelefono.setText(encargadoAuxi.getTelefono());
                            try {
                                switch (encargadoAuxi.getCondicionEconomica()) {
                                    case "Ingresos inferiores a Q 1,000":
                                        radioIngresos1.setSelected(true);
                                        break;
                                    case "Ingresos superiores a Q 1,000":
                                        radioIngresos2.setSelected(true);
                                        break;
                                    case "No tiene ingresos fijos":
                                        radioIngresos3.setSelected(true);
                                        break;
                                    default:
                                        break;
                                }
                            } catch (Exception ex) {
                                System.out.println(ex.getMessage());
                            }
                            System.out.println(encargadoAuxi.getCondicionEconomica());
                        }
                        txtNameEncargado.requestFocus();
                    } else if (e.getComponent().equals(txtNameEncargado)) {
                        txtTelefono.requestFocus();
                    } else if (e.getComponent().equals(txtTelefono)) {
                        txtDireccion.requestFocus();
                    } else if (e.getComponent().equals(txtdpiTerapista)) {
                        txtNombreTerapista.requestFocus();
                    }
                }
            }
        };
        auxiText.addKeyListener(focus);
        txtName.addKeyListener(focus);
        txtCarne.addKeyListener(focus);
        txtAge.addKeyListener(focus);
        txtDireccion.addKeyListener(focus);
        txtDpiEncargado.addKeyListener(focus);
        txtTelefono.addKeyListener(focus);
        txtNameEncargado.addKeyListener(focus);
        dateChooser.addKeyListener(focus);
        txtdpiTerapista.addKeyListener(focus);
        txtNombreTerapista.addKeyListener(focus);
    }

    private void llenarCondiciones(JList<String> listCondiciones) {
        listCondiciones.setListData(controlDatos.getCondiciones());
    }

    private void llenarComboTerapista(JComboBox comboTerapistas) {
        for (Terapista t : controlDatos.getTerapistaDB().getTerapistas()) {
            comboTerapistas.addItem(t.toString());
        }
    }

    private void agregarOtrasCondiciones() {
        for (int i = 0; i < listCondiciones.getSelectedValuesList().size(); i++) {
            controlDatos.getCondicionPacienteDB().insert(
                    CondicionPaciente.builder().
                            nombreCondicion(listCondiciones.getSelectedValuesList().get(i)).
                            carnePaciente(txtCarne.getText()).
                            build());
        }
    }

    private void agregarPaciente() {

    }

    private void llenarTablaPacientes(List<PacienteInfo> listPacientes) {
        dfModel = (DefaultTableModel) tablePacientes.getModel();
        dfModel.setRowCount(0);
        for (int i = 0; i < listPacientes.size(); i++) {
            String[] data = new String[]{
                listPacientes.get(i).getCarne(),
                listPacientes.get(i).getNombre(),
                listPacientes.get(i).getFecha(),
                listPacientes.get(i).getTipoPrograma(),
                listPacientes.get(i).getTerapista(),
                listPacientes.get(i).getTerapia(),
                listPacientes.get(i).getEcargado(),
                listPacientes.get(i).getTelefono()
            };
            dfModel.addRow(data);
        }
    }

    private void llenarTablaTerapistas(List<Terapista> terapistas) {
        dfModel = (DefaultTableModel) tableTerapistas.getModel();
        dfModel.setRowCount(0);
        for (Terapista terapista : terapistas) {
            String[] data = new String[]{terapista.getDpi(), terapista.getNombre()};
            dfModel.addRow(data);
        }
    }
}
